const bookExplanations: { [key: number]: string } = {
    1: `The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, near New York City, the novel depicts first-person narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession to reunite with his former lover, Daisy Buchanan.
The novel was inspired by a youthful romance Fitzgerald had with socialite Ginevra King, and the riotous parties he attended on Long Island's North Shore in 1922. Following a move to the French Riviera, Fitzgerald completed a rough draft of the novel in 1924. He submitted it to editor Maxwell Perkins, who persuaded Fitzgerald to revise the work over the following winter. After making revisions, Fitzgerald was satisfied with the text, but remained ambivalent about the book's title and considered several alternatives. Painter Francis Cugat's dust jacket art, named Celestial Eyes, greatly impressed Fitzgerald, and he incorporated its imagery into the novel.`,
    2:`Pride and Prejudice is the second novel by English author Jane Austen, published in 1813. A novel of manners, it follows the character development of Elizabeth Bennet, the protagonist of the book, who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness.
    Mr Bennet, owner of the Longbourn estate in Hertfordshire, has five daughters, but his property is entailed and can only be passed to a male heir. His wife also lacks an inheritance, so his family faces becoming poor upon his death. Thus, it is imperative that at least one of the daughters marry well to support the others, which is a primary motivation driving the plot.
    Pride and Prejudice has consistently appeared near the top of lists of "most-loved books" among literary scholars and the reading public. It has become one of the most popular novels in English literature, with over 20 million copies sold, and has inspired many derivatives in modern literature. For more than a century, dramatic adaptations, reprints, unofficial sequels, films, and TV versions of Pride and Prejudice have portrayed the memorable characters and themes of the novel, reaching mass audiences.
    `,
    3: `Crime and Punishment (pre-reform Russian: Преступленіе и наказаніе; post-reform Russian: Преступление и наказание, romanized: Prestupleniye i nakazaniye, IPA: [prʲɪstʊˈplʲenʲɪje ɪ nəkɐˈzanʲɪje]) is a novel by the Russian author Fyodor Dostoevsky. It was first published in the literary journal The Russian Messenger in twelve monthly installments during 1866.[1] It was later published in a single volume. It is the second of Dostoevsky's full-length novels following his return from ten years of exile in Siberia. Crime and Punishment is considered the first great novel of his mature period of writing[2] and is often cited as one of the greatest works of world literature.[3][4][5][6]
    Crime and Punishment follows the mental anguish and moral dilemmas of Rodion Raskolnikov, an impoverished ex-student in Saint Petersburg who plans to kill an unscrupulous pawnbroker, an old woman who stores money and valuable objects in her flat. He theorises that with the money he could liberate himself from poverty and go on to perform great deeds, and seeks to convince himself that certain crimes are justifiable if they are committed in order to remove obstacles to the higher goals of 'extraordinary' men. Once the deed is done, however, he finds himself wracked with confusion, paranoia, and disgust. His theoretical justifications lose all their power as he struggles with guilt and horror and is confronted with both internal and external consequences of his deed.`,
    4:`To Kill a Mockingbird is a novel by the American author Harper Lee. It was published in June 1960 and became instantly successful. In the United States, it is widely read in high schools and middle schools. To Kill a Mockingbird has become a classic of modern American literature; a year after its release, it won the Pulitzer Prize. The plot and characters are loosely based on Lee's observations of her family, her neighbors and an event that occurred near her hometown of Monroeville, Alabama, in 1936, when she was ten.
    Despite dealing with the serious issues of rape and racial inequality, the novel is renowned for its warmth and humor. Atticus Finch, the narrator's father, has served as a moral hero for many readers and as a model of integrity for lawyers. The historian Joseph Crespino explains, "In the twentieth century, To Kill a Mockingbird is probably the most widely read book dealing with race in America, and its main character, Atticus Finch, the most enduring fictional image of racial heroism."[1] As a Southern Gothic novel and Bildungsroman, the primary themes of To Kill a Mockingbird involve racial injustice and the destruction of innocence. Scholars have noted that Lee also addresses issues of class, courage, compassion, and gender roles in the Deep South. Lessons from the book emphasize tolerance and decry prejudice.[2] Despite its themes, To Kill a Mockingbird has been subject to campaigns for removal from public classrooms, often challenged for its use of racial epithets. In 2006, British librarians ranked the book ahead of the Bible as one "every adult should read before they die".[3]
    `,
    5:`The Catcher in the Rye is a novel by American author J. D. Salinger that was partially published in serial form in 1945–46 before being novelized in 1951. Originally intended for adults, it is often read by adolescents for its themes of angst and alienation, and as a critique of superficiality in society.[4][5] The novel also deals with themes of innocence, identity, belonging, loss, connection, sex, and depression. The main character, Holden Caulfield, has become an icon for teenage rebellion.[6] Caulfield, nearly of age, gives his opinion on a wide variety of topics as he narrates his recent life events.
    The Catcher in the Rye has been translated widely.[7] About one million copies are sold each year, with total sales of more than 65 million books.[8] The novel was included on Time's 2005 list of the 100 best English-language novels written since 1923,[9] and it was named by Modern Library and its readers as one of the 100 best English-language novels of the 20th century.[10][11][12] In 2003, it was listed at number 15 on the BBC's survey "The Big Read".
    `,
    6:`Nineteen Eighty-Four (also published as 1984) is a dystopian novel and cautionary tale by English writer George Orwell. It was published on 8 June 1949 by Secker & Warburg as Orwell's ninth and final book completed in his lifetime. Thematically, it centres on the consequences of totalitarianism, mass surveillance, and repressive regimentation of people and behaviours within society.[3][4] Orwell, a staunch believer in democratic socialism and member of the anti-Stalinist Left, modelled the Britain under authoritarian socialism in the novel on the Soviet Union in the era of Stalinism and on the very similar practices of both censorship and propaganda in Nazi Germany.[5] More broadly, the novel examines the role of truth and facts within societies and the ways in which they can be manipulated.
    `,
    7:`Moby-Dick; or, The Whale is an 1851 novel by American writer Herman Melville. The book is the sailor Ishmael's narrative of the maniacal quest of Ahab, captain of the whaling ship Pequod, for vengeance against Moby Dick, the giant white sperm whale that bit off his leg on the ship's previous voyage. A contribution to the literature of the American Renaissance, Moby-Dick was published to mixed reviews, was a commercial failure, and was out of print at the time of the author's death in 1891. Its reputation as a Great American Novel was established only in the 20th century, after the 1919 centennial of its author's birth. William Faulkner said he wished he had written the book himself,[1] and D. H. Lawrence called it "one of the strangest and most wonderful books in the world" and "the greatest book of the sea ever written".[2] Its opening sentence, "Call me Ishmael", is among world literature's most famous.[3]
    `,
    8:`War and Peace (Russian: Война и мир, romanized: Voyna i mir; pre-reform Russian: Война и миръ; [vɐjˈna i ˈmʲir]) is a literary work by Russian author Leo Tolstoy. Set during the Napoleonic Wars, the work mixes fictional narrative with chapters discussing history and philosophy. An early version was published serially beginning in 1865, after which the entire book was rewritten and published in 1869. It is regarded, with Anna Karenina, as Tolstoy's finest literary achievement and remains an internationally praised classic of world literature.[1][2][3]
    The book chronicles the French invasion of Russia and its aftermath during the Napoleonic era. It uses five interlocking narratives following different Russian aristocratic families to illustrate Napoleon's impact on Tsarist society. Portions of an earlier version, titled The Year 1805,[4] were serialized in The Russian Messenger from 1865 to 1867 before the novel was published in its entirety in 1869.[5]
    Tolstoy said that the best Russian literature does not conform to standards and hence hesitated to classify War and Peace, saying it is "not a novel, even less is it a poem, and still less a historical chronicle." Large sections, especially the later chapters, are philosophical discussions rather than narrative.[6] He regarded Anna Karenina as his first true novel.
    `,
    9:`Alice's Adventures in Wonderland (commonly Alice in Wonderland) is an 1865 English children's novel by Lewis Carroll, a mathematics don at the University of Oxford. It details the story of a girl named Alice who falls through a rabbit hole into a fantasy world of anthropomorphic creatures. It is seen as an example of the literary nonsense genre. The artist John Tenniel provided 42 wood-engraved illustrations for the book.
    It received positive reviews upon release and is now one of the best-known works of Victorian literature; its narrative, structure, characters and imagery have had a widespread influence on popular culture and literature, especially in the fantasy genre.[1][2] It is credited as helping end an era of didacticism in children's literature, inaugurating an era in which writing for children aimed to "delight or entertain".[3] The tale plays with logic, giving the story lasting popularity with adults as well as with children.[4] The titular character Alice shares her name with Alice Liddell, a girl Carroll knew—scholars disagree about the extent to which the character was based upon her.[5][6]
    The book has never been out of print and has been translated into 174 languages. Its legacy covers adaptations for screen, radio, art, ballet, opera, musicals, theme parks, board games and video games.[7] Carroll published a sequel in 1871 entitled Through the Looking-Glass and a shortened version for young children, The Nursery "Alice", in 1890.`,
    10:`Jane Eyre (originally published as Jane Eyre: An Autobiography) is a novel by the English writer Charlotte Brontë. It was published under her pen name "Currer Bell" on 19 October 1847 by Smith, Elder & Co. of London. The first American edition was published the following year by Harper & Brothers of New York.[2] Jane Eyre is a bildungsroman that follows the experiences of its eponymous heroine, including her growth to adulthood and her love for Mr Rochester, the brooding master of Thornfield Hall.
    `,
    11:`Great Expectations is the thirteenth novel by Charles Dickens and his penultimate completed novel. The novel is a Bildungsroman and depicts the education of an orphan nicknamed Pip. It is Dickens' second novel, after David Copperfield, to be fully narrated in the first person.[N 1] The novel was first published as a serial in Dickens's weekly periodical All the Year Round, from 1 December 1860 to August 1861.[1] In October 1861, Chapman & Hall published the novel in three volumes.[2][3][4]
    The novel is set in Kent and London in the early to mid-19th century[5] and contains some of Dickens's most celebrated scenes, starting in a graveyard, where the young Pip is accosted by the escaped convict Abel Magwitch. Great Expectations is full of extreme imagery—poverty, prison ships and chains, and fights to the death—and has a colourful cast of characters who have entered popular culture. These include the eccentric Miss Havisham, the beautiful but cold Estella, and Joe Gargery, the unsophisticated and kind blacksmith. Dickens's themes include wealth and poverty, love and rejection, and the eventual triumph of good over evil. Great Expectations, which is popular with both readers and literary critics,[6][7] has been translated into many languages and adapted numerous times into various media.
    `,
    12:`Adventures of Huckleberry Finn is a novel by American author Mark Twain, which was first published in the United Kingdom in December 1884 and in the United States in February 1885.
    Commonly named among the Great American Novels, the work is among the first in major American literature to be written throughout in vernacular English, characterized by local color regionalism. It is told in the first person by Huckleberry "Huck" Finn, the narrator of two other Twain novels (Tom Sawyer Abroad and Tom Sawyer, Detective) and a friend of Tom Sawyer. It is a direct sequel to The Adventures of Tom Sawyer.
    The book is noted for "changing the course of children's literature" in the United States for the "deeply felt portrayal of boyhood".[2] [better source needed] It is also known for its colorful description of people and places along the Mississippi River. Set in a Southern antebellum society that had ceased to exist over 20 years before the work was published, Adventures of Huckleberry Finn is an often scathing satire on entrenched attitudes, particularly racism and freedom.
    `,
    13:`Wuthering Heights is the only novel by the English author Emily Brontë, initially published in 1847 under her pen name "Ellis Bell". It concerns two families of the landed gentry living on the West Yorkshire moors, the Earnshaws and the Lintons, and their turbulent relationships with the Earnshaws' foster son, Heathcliff. The novel was influenced by Romanticism and Gothic fiction.
    Wuthering Heights is now widely considered to be one of the greatest novels ever written in English, but contemporaneous reviews were polarised. It was controversial for its depictions of mental and physical cruelty, including domestic abuse, and for its challenges to Victorian morality, religion, and the class system.[1][2]
    `,
    14:`The Picture of Dorian Gray is a philosophical novel by Irish writer Oscar Wilde. A shorter novella-length version was published in the July 1890 issue of the American periodical Lippincott's Monthly Magazine.[1][2] The novel-length version was published in April 1891.
    The story revolves around a portrait of Dorian Gray painted by Basil Hallward, a friend of Dorian's and an artist infatuated with Dorian's beauty. Through Basil, Dorian meets Lord Henry Wotton and is soon enthralled by the aristocrat's hedonistic worldview: that beauty and sensual fulfillment are the only things worth pursuing in life. Newly understanding that his beauty will fade, Dorian expresses the desire to sell his soul, to ensure that the picture, rather than he, will age and fade. The wish is granted, and Dorian pursues a libertine life of varied amoral experiences while staying young and beautiful; all the while, his portrait ages and visually records every one of Dorian's sins.[3]
    Wilde's only novel, it was subject to much controversy and criticism in its time but has come to be recognized as a classic of Gothic literature.
    `,
    15:`Don Quixote[a][b][c] is a Spanish epic novel by Miguel de Cervantes. It was originally published in two parts, in 1605 and 1615. Considered a founding work of Western literature, it is often labelled as the first modern novel[2][3] and the greatest work ever written.[4][5] Don Quixote is also one of the most-translated books in the world[6] and one of the best-selling novels of all time.
    `,
    16:`Anna Karenina (Russian: Анна Каренина, IPA: [ˈanːə kɐˈrʲenʲɪnə])[1] is a novel by the Russian author Leo Tolstoy, first published in book form in 1878. Widely considered to be the greatest work of literature ever written,[2] Tolstoy himself called it his first true novel. It was initially released in serial installments from 1875 to 1877, all but the last part appearing in the periodical The Russian Messenger.[3] When William Faulkner was asked to list what he thought were the three greatest novels, he replied: "Anna Karenina, Anna Karenina, and Anna Karenina".[4]
    `,
    17:`Frankenstein; or, The Modern Prometheus is an 1818 novel written by English author Mary Shelley. Frankenstein tells the story of Victor Frankenstein, a young scientist who creates a sapient creature in an unorthodox scientific experiment. Shelley started writing the story when she was 18, and the first edition was published anonymously in London on 1 January 1818, when she was 20. Her name first appeared in the second edition, which was published in Paris in 1821.`,
    18:`The Brothers Karamazov (Russian: Братья Карамазовы, Brat'ya Karamazovy, pronounced [ˈbratʲjə kərɐˈmazəvɨ]), also translated as The Karamazov Brothers, is the last novel by Russian author Fyodor Dostoevsky. Dostoevsky spent nearly two years writing The Brothers Karamazov, which was published as a serial in The Russian Messenger from January 1879 to November 1880. Dostoevsky died less than four months after its publication. It has been acclaimed as one of the supreme achievements in world literature.
    Set in 19th-century Russia, The Brothers Karamazov is a passionate philosophical novel that discusses questions of God, free will, and morality. It has also been described as a theological drama[1] dealing with problems of faith, doubt, and reason in the context of a modernizing Russia, with a plot that revolves around the subject of patricide. Dostoevsky composed much of the novel in Staraya Russa, which inspired the main setting.[2]`,
    19:`The Grapes of Wrath is an American realist novel written by John Steinbeck and published in 1939.[2] The book won the National Book Award[3] and Pulitzer Prize[4] for fiction, and it was cited prominently when Steinbeck was awarded the Nobel Prize in Literature in 1962.[5]
    Set during the Great Depression, the novel focuses on the Joads, a poor family of tenant farmers driven from their Oklahoma home by drought, economic hardship, agricultural industry changes, and bank foreclosures forcing tenant farmers out of work. Due to their nearly hopeless situation, and in part because they are trapped in the Dust Bowl, the Joads set out for California on the "mother road", along with thousands of other "Okies" seeking jobs, land, dignity, and a future.
    The Grapes of Wrath is frequently read in American high school and college literature classes due to its historical context and enduring legacy.[6] A celebrated Hollywood film version, starring Henry Fonda and directed by John Ford, was released in 1940.`,
    20:`The Scarlet Letter: A Romance is a work of historical fiction by American author Nathaniel Hawthorne, published in 1850.[1] Set in the Puritan Massachusetts Bay Colony during the years 1642 to 1649, the novel tells the story of Hester Prynne, who conceives a daughter with a man to whom she is not married and then struggles to create a new life of repentance and dignity. As punishment, she must wear a scarlet letter 'A' (for "adultery"). Containing a number of religious and historic allusions, the book explores themes of legalism, sin and guilt.`,
    21:`The Girl with the Dragon Tattoo (original title in Swedish: Män som hatar kvinnor, lit. 'Men Who Hate Women') is a psychological thriller novel by Swedish author and journalist Stieg Larsson (1954–2004). It was published posthumously in 2005, translated into English in 2008, and became an international bestseller.[1]
    The Girl with the Dragon Tattoo is the first book of the Millennium series. Originally a trilogy by Larsson, the series was expanded to another three books by David Lagercrantz, and as of 2021 rights had been sold for Karin Smirnoff to write three more.`,
    22:`Gone Girl is a 2012 crime thriller novel by American writer Gillian Flynn. It was published by Crown Publishing Group in June 2012. The novel was popular and made the New York Times Best Seller list. The sense of suspense in the novel comes from whether Nick Dunne is responsible for the disappearance of his wife Amy.
    Critics in the United States positively received and reviewed the novel, noting the author's use of unreliable narration, plot twists, and suspense.
    A film adaptation was released on 3 October 2014, with screenplay by Flynn herself. It was directed by David Fincher, with Ben Affleck and Rosamund Pike in lead roles. The film enjoyed commercial success and widespread critical acclaim.`,
    23:`The Hound of the Baskervilles is the third of the four crime novels by British writer Arthur Conan Doyle featuring the detective Sherlock Holmes. Originally serialised in The Strand Magazine from August 1901 to April 1902, it is set largely in Dartmoor, Devon, in England's West Country and follows Holmes and Watson investigating the legend of a fearsome, diabolical hound of supernatural origin. This was the first appearance of Holmes since his apparent death in "The Final Problem", and the success of The Hound of the Baskervilles led to the character's eventual revival.[3]
    One of the most famous stories ever written,[3] in 2003, the book was listed as number 128 of 200 on the BBC's The Big Read poll of the UK's "best-loved novel".[4] In 1999, a poll of "Sherlockians" ranked it as the best of the four Holmes novels.[5]`,
    24:`Big Little Lies is a 2014 novel written by Liane Moriarty. It was published in July 2014 by Penguin Publishing.[1] The novel made the New York Times Best Seller list.[2] In 2015, it was a recipient of the Davitt Award.`,
    25:`The Da Vinci Code is a 2003 mystery thriller novel by Dan Brown. It is Brown's second novel to include the character Robert Langdon: the first was his 2000 novel Angels & Demons. The Da Vinci Code follows symbologist Langdon and cryptologist Sophie Neveu after a murder in the Louvre Museum in Paris entangles them in a dispute between the Priory of Sion and Opus Dei over the possibility of Jesus and Mary Magdalene having had a child together.`,
    26:`The Lord of the Rings is an epic[1] high fantasy novel[a] by the English author and scholar J. R. R. Tolkien. Set in Middle-earth, the story began as a sequel to Tolkien's 1937 children's book The Hobbit, but eventually developed into a much larger work. Written in stages between 1937 and 1949, The Lord of the Rings is one of the best-selling books ever written, with over 150 million copies sold.[2]
    The title refers to the story's main antagonist,[b] Sauron, the Dark Lord who in an earlier age created the One Ring to rule the other Rings of Power given to Men, Dwarves, and Elves, in his campaign to conquer all of Middle-earth. From homely beginnings in the Shire, a hobbit land reminiscent of the English countryside, the story ranges across Middle-earth, following the quest to destroy the One Ring, seen mainly through the eyes of the hobbits Frodo, Sam, Merry, and Pippin. Aiding Frodo are the Wizard Gandalf, the Men Aragorn and Boromir, the Elf Legolas, and the Dwarf Gimli, who unite in order to rally the Free Peoples of Middle-earth against Sauron's armies and give Frodo a chance to destroy the One Ring in the fire of Mount Doom.`,
    27:`Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school and with the help of his friends, Ron Weasley and Hermione Granger, he faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.`,
    28:`A Song of Ice and Fire is a series of epic fantasy novels by the American novelist and screenwriter George R. R. Martin. He began writing the first volume, A Game of Thrones, in 1991, publishing it in 1996. Martin originally envisioned the series as a trilogy but has released five out of a planned seven volumes. The fifth and most recent entry in the series, A Dance with Dragons, was published in 2011. Martin continues to write the sixth novel, titled The Winds of Winter. A seventh novel, A Dream of Spring, is planned to follow.
    A Song of Ice and Fire depicts a violent world dominated by political realism. What little supernatural power exists is confined to the margins of the known world. Moral ambiguity pervades the books and their stories continually raise questions concerning loyalty, pride, human sexuality, piety, and the morality of violence.`,
    29:`The Name of the Wind, also referred to as The Kingkiller Chronicle: Day One, is a heroic fantasy novel written by American author Patrick Rothfuss. It is the first book in the ongoing fantasy trilogy The Kingkiller Chronicle, followed by The Wise Man's Fear. It was published on March 27, 2007, by DAW Books.`,
    30:`Mistborn: The Final Empire, also known simply as Mistborn or The Final Empire, is a fantasy novel written by American author Brandon Sanderson. It was published on July 17, 2006, by Tor Books and is the first novel in the Mistborn trilogy, followed by The Well of Ascension in 2007 and The Hero of Ages in 2008.`,
    31:`Dune is a 1965 epic science fiction novel by American author Frank Herbert, originally published as two separate serials (1963–64 novel Dune World and 1965 novel Prophet of Dune) in Analog magazine. It tied with Roger Zelazny's This Immortal for the Hugo Award for Best Novel and won the inaugural Nebula Award for Best Novel in 1966. It is the first installment of the Dune Chronicles. It is one of the world's best-selling science fiction novels.[2]`,
    32:`Neuromancer is a 1984 science fiction novel by American-Canadian writer William Gibson. Considered one of the earliest and best-known works in the cyberpunk genre, it is the only novel to win the Nebula Award, the Philip K. Dick Award, and the Hugo Award.[1] It was Gibson's debut novel and the beginning of the Sprawl trilogy. Set in the future, the novel follows Henry Case, a washed-up hacker hired for one last job, which brings him in contact with a powerful artificial intelligence.`,
    33:`The Martian is a 2011 science fiction debut novel written by Andy Weir. The book was originally self-published on Weir's blog, in a serialized format.[1] In 2014, the book was re-released after Crown Publishing Group purchased the exclusive publishing rights. The story follows an American astronaut, Mark Watney, as he becomes stranded alone on Mars in 2035[2] and must improvise in order to survive.[3][4][5]
    A film adaptation, The Martian, directed by Ridley Scott and starring Matt Damon, was released in October 2015.[6]`,
    34:`The Foundation series is a science fiction book series written by American author Isaac Asimov. First published as a series of short stories and novellas in 1942–50, and subsequently in three collections in 1951–53, for nearly thirty years the series was a trilogy: Foundation (1951); Foundation and Empire (1952); and Second Foundation (1953). It won the one-time Hugo Award for "Best All-Time Series" in 1966.[1][2] Asimov later added new volumes, with two sequels: Foundation's Edge (1982) and Foundation and Earth (1986), and two prequels: Prelude to Foundation (1988) and Forward the Foundation (1993).
    The premise of the stories is that in the waning days of a future Galactic Empire, the mathematician Hari Seldon spends his life developing a theory of psychohistory, a new and effective mathematics of sociology. Using statistical laws of mass action, it can predict the future of large populations. Seldon foresees the imminent fall of the Empire, which encompasses the entire Milky Way, and a Dark Age lasting 30,000 years before a second empire arises. Although the momentum of the Empire's fall is too great to stop, Seldon devises a plan by which "the onrushing mass of events must be deflected just a little" to eventually limit this interregnum to just one thousand years.
    `,
    35:`The Notebook is the debut novel by American novelist Nicholas Sparks. Released in 1996, the romance novel was later adapted into a popular 2004 film of the same name.
    `,
    36:`Outlander is a series of historical fantasy novels by American author Diana Gabaldon.[1] Gabaldon began the first volume of the series, Outlander, in the late 1980s, and it was published in 1991.[2] She has published nine out of a planned ten volumes.[3] The ninth novel in the series, Go Tell the Bees That I Am Gone, was released on November 23, 2021.[4]
    The Outlander series focuses on 20th-century British nurse Claire Randall, who time travels to 18th-century Scotland and finds adventure and romance with the dashing Highland warrior Jamie Fraser. The books have sold over 50 million copies worldwide as of 2021.[5]
    `,
    37:`Me Before You is a romance novel written by Jojo Moyes. The book was first published on 5 January 2012 in the United Kingdom. A sequel titled After You was released on 24 September 2015 through Pamela Dorman Books.[1][2] A second sequel, Still Me, was published in January 2018. 
    `,
    38:`The Fault in Our Stars is a novel by John Green. It is his fourth solo novel, and sixth novel overall. It was published on January 10, 2012. The title is inspired by Act 1, Scene 2 of Shakespeare's play Julius Caesar, in which the nobleman Cassius says to Brutus: "Men at some time were masters of their fates, / The fault, dear Brutus, is not in our stars, / But in ourselves, that we are underlings." The story is narrated by Hazel Grace Lancaster, a 16-year-old girl with thyroid cancer that has affected her lungs. Hazel is forced by her parents to attend a support group where she subsequently meets and falls in love with 17-year-old Augustus Waters, an ex-basketball player, amputee, and survivor of osteosarcoma.
    `,
    39:`The Silence of the Lambs is a 1988 psychological horror novel by Thomas Harris. Published August 29, it is the sequel to Harris's 1981 novel Red Dragon and both novels feature the cannibalistic serial killer and brilliant psychiatrist Dr. Hannibal Lecter. This time, however, he is pitted against FBI trainee Clarice Starling as she works to solve the case of the "Buffalo Bill" serial killer. It is the most well-known installment of Harris' Hannibal Lecter series, selling over 10 million copies.
    The film adaptation directed by Jonathan Demme was released in 1991 to widespread critical acclaim and box office success. It won all five of the "Big Five" Academy Awards becoming one of only 3 films ever, and the first film since One Flew Over the Cuckoo's Nest in 1975 to have done so. It is also the only horror film to win Best Picture at the Oscars.
    `,
    40:`The Magician's Nephew is a portal fantasy children's novel by C. S. Lewis, published in 1955 by The Bodley Head. It is the sixth published of seven novels in The Chronicles of Narnia (1950–1956). In recent editions, which sequence the books according to Narnia history, it is volume one of the series. Like the others, it was illustrated by Pauline Baynes whose work has been retained in many later editions. The Bodley Head was a new publisher for The Chronicles, a change from Geoffrey Bles who had published the previous five novels.[1][3]
    `,
    41:`Brave New World is a dystopian novel by English author Aldous Huxley, written in 1931 and published in 1932.[3] Largely set in a futuristic World State, whose citizens are environmentally engineered into an intelligence-based social hierarchy, the novel anticipates huge scientific advancements in reproductive technology, sleep-learning, psychological manipulation and classical conditioning that are combined to make a dystopian society which is challenged by the story's protagonist. Huxley followed this book with a reassessment in essay form, Brave New World Revisited (1958), and with his final novel, Island (1962), the utopian counterpart. This novel is often compared as an inversion counterpart to George Orwell's 1984 (1949).
    `,
    42:`Gone with the Wind is a novel by American writer Margaret Mitchell, first published in 1936. The story is set in Clayton County and Atlanta, both in Georgia, during the American Civil War and Reconstruction Era. It depicts the struggles of young Scarlett O'Hara, the spoiled daughter of a well-to-do plantation owner, who must use every means at her disposal to claw her way out of poverty following Sherman's destructive "March to the Sea." This historical novel features a coming-of-age story, with the title taken from the poem "Non Sum Qualis eram Bonae Sub Regno Cynarae", written by Ernest Dowson.`,

    
  };
  
  export default bookExplanations;
  